# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload App Store Metadata"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_app_version_update: true,

      skip_screenshots: true,

      force: true,
    )
  end
end
